include: "rules/common.smk"


rule all:
    input:
        get_targets(),


include: "rules/sra/prefetch.smk"
include: "rules/sra/fasterq-dump.smk"
include: "rules/sra/pigz.smk"
include: "rules/qc/qc.smk"
