include: "rules/common.smk"


rule all:
    input:
        get_targets(),


if config["source_download"] == "sra":

    include: "rules/sra/prefetch.smk"
    include: "rules/sra/fasterq-dump.smk"
    include: "rules/sra/pigz.smk"
    include: "rules/qc/qc.smk"

elif config["source_download"] == "gdc":

    include: f"rules/gdc/slicing-{config['method_gdc']}.smk"
