dir_run: /home/username/projects/data/sra/PRJNA871228

retries_sra: 1

suffixes_fastq_renamed:
  paired-end:
    - "_R1.fq.gz"
    - "_R2.fq.gz"
  single-end: ".fq.gz"

run_fastqc: true
run_multiqc: true
