software-deployment-method:
  - conda
conda-prefix: /.snakemake/envs/smk_downloader
printshellcmds: True
keep-incomplete: True
prioritize: ["pigz_paired_end", "pigz_single_end"]
cores: 20
resources:
  n_prefetch: 5
set-threads:
  fastqc: 4
  fasterq_dump_paired_end: 10
  fasterq_dump_single_end: 10
  pigz_paired_end: 10
  pigz_single_end: 10
set-resources:
  prefetch:
    n_prefetch: 1
