$schema: https://json-schema.org/draft/2020-12/schema
type: object
properties:
  dir_run:
    type: string
  retries_prefetch:
    type: integer
    default: 1
  suffixes_fastq_renamed:
    type: object
    properties:
      paired-end:
        type: array
        items:
          type: string
        default:
          - "_R1.fq.gz"
          - "_R2.fq.gz"
      single-end:
        type: string
        default: ".fq.gz"
    default:
      paired-end:
        - "_R1.fq.gz"
        - "_R2.fq.gz"
      single-end: ".fq.gz"
  run_fastqc:
    type: boolean
    default: true
  run_multiqc:
    type: boolean
    default: true
additionalProperties: false
